name: pbp_2_restaurant
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 2.3.3
  sqflite: ^2.2.6
  flutter_slidable: ^0.6.0
  smooth_page_indicator: ^1.0.0+2
  checkbox_formfield: ^0.2.0
  clippy_flutter: ^2.0.0-nullsafety.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_tts: ^3.8.3
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.1.1
  camera: ^0.10.5+2 #access to hardware
  mobile_scanner: ^3.2.0 #scan qr code
  path_provider: ^2.0.15 #generate path to save file
  qr_flutter: ^4.1.0
  gallery_saver: ^2.3.2
  geolocator: ^8.0.1
  url_launcher: ^6.1.14
  geocoding: ^2.0.1
  image_picker: ^1.0.4
  pdf: ^3.10.6
  printing: ^5.11.1
  intl: ^0.18.1
  uuid: ^4.2.1
  barcode_widget: ^2.0.4
  responsive_sizer: ^3.2.0
  http: ^0.13.6
  flutter_riverpod: ^2.4.8
  http_client: ^1.5.2
  go_router: ^12.1.1
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  toast: ^0.3.0
  fluttertoast: ^8.2.4
  sqflite_common_ffi: ^2.3.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash/splash_image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/burger/beef-burger-deluxe.png
    - assets/images/burger/beef-burger.png
    - assets/images/burger/bigmac.png
    - assets/images/burger/cheeseburger-deluxe.png
    - assets/images/burger/cheeseburger.png
    - assets/images/burger/chicken-muffin-with-egg.png
    - assets/images/burger/chicken-muffin.png
    - assets/images/burger/egg-and-cheese-muffin.png
    - assets/images/test.jpeg
    - assets/images/Dessert.png
    - assets/images/Drink.png
    - assets/images/Humberger.png
    - assets/images/Meat.png
    - assets/images/Noodles.png
    - assets/images/Pizza.png
    - assets/images/Salad.png
    - assets/images/Snack.png
    - assets/images/Banner-Home.png
    - assets/images/images1.jpg
    - assets/images/images2.jpg
    - assets/images/appBarView_images/Burger.jpeg
    - assets/images/appBarView_images/EsJeruk.jpeg
    - assets/images/appBarView_images/EsTeh.jpeg
    - assets/images/appBarView_images/FrenchFries.jpeg
    - assets/images/appBarView_images/Pizza.jpeg
    - assets/images/appBarView_images/PrettyDog.jpeg
    - assets/images/appBarView_images/Spaghetti.jpeg
    - assets/ilustrations/ilustration-1.png
    - assets/ilustrations/ilustration-2.png
    - assets/ilustrations/pattern.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/splash/splash_image.png
    - assets/images/categories/cat-chicken.png
    - assets/images/categories/cat-drinks.jpeg
    - assets/images/etc/rica-chicken-rice.png

linter:
  rules:
    - depend_on_referenced_packages

msix_config:
  display_name: resto
  publisher_display_name: restp
  identity_name:
  logo_path:
  msix_version: 1.0.0.0
  capabilities: internetClient
