name: pbp_2_restaurant
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  google_fonts: 2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/burger/beef-burger-deluxe.png
    - assets/images/burger/beef-burger.png
    - assets/images/burger/bigmac.png
    - assets/images/burger/cheeseburger-deluxe.png
    - assets/images/burger/cheeseburger.png
    - assets/images/burger/chicken-muffin-with-egg.png
    - assets/images/burger/chicken-muffin.png
    - assets/images/burger/egg-and-cheese-muffin.png
    - assets/images/test.jpeg
    - assets/images/Dessert.png
    - assets/images/Drink.png
    - assets/images/Humberger.png
    - assets/images/Meat.png
    - assets/images/Noodles.png
    - assets/images/Pizza.png
    - assets/images/Salad.png
    - assets/images/Snack.png
    - assets/images/Banner-Home.png

linter:
  rules:
    - depend_on_referenced_packages